/** รายชื่อ 77 จังหวัดของไทย สำหรับ Dropdown "จังหวัด" ตอนปิดการขายสำเร็จ (คอลัมน์ Province ในชีต Revenue) */
var THAI_PROVINCES = [
  'กรุงเทพมหานคร', 'กระบี่', 'กาญจนบุรี', 'กาฬสินธุ์', 'กำแพงเพชร', 'ขอนแก่น', 'จันทบุรี', 'ฉะเชิงเทรา',
  'ชลบุรี', 'ชัยนาท', 'ชัยภูมิ', 'ชุมพร', 'เชียงราย', 'เชียงใหม่', 'ตรัง', 'ตราด', 'ตาก', 'นครนายก',
  'นครปฐม', 'นครพนม', 'นครราชสีมา', 'นครศรีธรรมราช', 'นครสวรรค์', 'นนทบุรี', 'นราธิวาส', 'น่าน',
  'บึงกาฬ', 'บุรีรัมย์', 'ปทุมธานี', 'ประจวบคีรีขันธ์', 'ปราจีนบุรี', 'ปัตตานี', 'พระนครศรีอยุธยา',
  'พะเยา', 'พังงา', 'พัทลุง', 'พิจิตร', 'พิษณุโลก', 'เพชรบุรี', 'เพชรบูรณ์', 'แพร่', 'ภูเก็ต',
  'มหาสารคาม', 'มุกดาหาร', 'แม่ฮ่องสอน', 'ยโสธร', 'ยะลา', 'ร้อยเอ็ด', 'ระนอง', 'ระยอง', 'ราชบุรี',
  'ลพบุรี', 'ลำปาง', 'ลำพูน', 'เลย', 'ศรีสะเกษ', 'สกลนคร', 'สงขลา', 'สตูล', 'สมุทรปราการ',
  'สมุทรสงคราม', 'สมุทรสาคร', 'สระแก้ว', 'สระบุรี', 'สิงห์บุรี', 'สุโขทัย', 'สุพรรณบุรี', 'สุราษฎร์ธานี',
  'สุรินทร์', 'หนองคาย', 'หนองบัวลำภู', 'อ่างทอง', 'อำนาจเจริญ', 'อุดรธานี', 'อุตรดิตถ์', 'อุทัยธานี', 'อุบลราชธานี',
];

/**
 * รายชื่อประเทศสำหรับ Dropdown "ประเทศที่จะส่งไปขาย"
 * code = ISO 3166-1 alpha-2, th = ชื่อไทย, en = ชื่ออังกฤษ
 */
var COUNTRIES = [
  { code: 'TH', th: 'ไทย', en: 'Thailand' },
  { code: 'LA', th: 'ลาว', en: 'Laos' },
  { code: 'MM', th: 'เมียนมา', en: 'Myanmar' },
  { code: 'KH', th: 'กัมพูชา', en: 'Cambodia' },
  { code: 'VN', th: 'เวียดนาม', en: 'Vietnam' },
  { code: 'MY', th: 'มาเลเซีย', en: 'Malaysia' },
  { code: 'SG', th: 'สิงคโปร์', en: 'Singapore' },
  { code: 'ID', th: 'อินโดนีเซีย', en: 'Indonesia' },
  { code: 'PH', th: 'ฟิลิปปินส์', en: 'Philippines' },
  { code: 'BN', th: 'บรูไน', en: 'Brunei' },
  { code: 'TL', th: 'ติมอร์-เลสเต', en: 'Timor-Leste' },
  { code: 'CN', th: 'จีน', en: 'China' },
  { code: 'HK', th: 'ฮ่องกง', en: 'Hong Kong' },
  { code: 'MO', th: 'มาเก๊า', en: 'Macau' },
  { code: 'TW', th: 'ไต้หวัน', en: 'Taiwan' },
  { code: 'JP', th: 'ญี่ปุ่น', en: 'Japan' },
  { code: 'KR', th: 'เกาหลีใต้', en: 'South Korea' },
  { code: 'KP', th: 'เกาหลีเหนือ', en: 'North Korea' },
  { code: 'MN', th: 'มองโกเลีย', en: 'Mongolia' },
  { code: 'IN', th: 'อินเดีย', en: 'India' },
  { code: 'PK', th: 'ปากีสถาน', en: 'Pakistan' },
  { code: 'BD', th: 'บังกลาเทศ', en: 'Bangladesh' },
  { code: 'LK', th: 'ศรีลังกา', en: 'Sri Lanka' },
  { code: 'NP', th: 'เนปาล', en: 'Nepal' },
  { code: 'BT', th: 'ภูฏาน', en: 'Bhutan' },
  { code: 'MV', th: 'มัลดีฟส์', en: 'Maldives' },
  { code: 'AF', th: 'อัฟกานิสถาน', en: 'Afghanistan' },
  { code: 'KZ', th: 'คาซัคสถาน', en: 'Kazakhstan' },
  { code: 'UZ', th: 'อุซเบกิสถาน', en: 'Uzbekistan' },
  { code: 'TM', th: 'เติร์กเมนิสถาน', en: 'Turkmenistan' },
  { code: 'TJ', th: 'ทาจิกิสถาน', en: 'Tajikistan' },
  { code: 'KG', th: 'คีร์กีซสถาน', en: 'Kyrgyzstan' },
  { code: 'AE', th: 'สหรัฐอาหรับเอมิเรตส์', en: 'United Arab Emirates' },
  { code: 'SA', th: 'ซาอุดีอาระเบีย', en: 'Saudi Arabia' },
  { code: 'QA', th: 'กาตาร์', en: 'Qatar' },
  { code: 'KW', th: 'คูเวต', en: 'Kuwait' },
  { code: 'BH', th: 'บาห์เรน', en: 'Bahrain' },
  { code: 'OM', th: 'โอมาน', en: 'Oman' },
  { code: 'JO', th: 'จอร์แดน', en: 'Jordan' },
  { code: 'IL', th: 'อิสราเอล', en: 'Israel' },
  { code: 'PS', th: 'ปาเลสไตน์', en: 'Palestine' },
  { code: 'LB', th: 'เลบานอน', en: 'Lebanon' },
  { code: 'IQ', th: 'อิรัก', en: 'Iraq' },
  { code: 'IR', th: 'อิหร่าน', en: 'Iran' },
  { code: 'YE', th: 'เยเมน', en: 'Yemen' },
  { code: 'SY', th: 'ซีเรีย', en: 'Syria' },
  { code: 'TR', th: 'ตุรกี', en: 'Turkey' },
  { code: 'CY', th: 'ไซปรัส', en: 'Cyprus' },
  { code: 'GE', th: 'จอร์เจีย', en: 'Georgia' },
  { code: 'AM', th: 'อาร์เมเนีย', en: 'Armenia' },
  { code: 'AZ', th: 'อาเซอร์ไบจาน', en: 'Azerbaijan' },
  { code: 'RU', th: 'รัสเซีย', en: 'Russia' },
  { code: 'UA', th: 'ยูเครน', en: 'Ukraine' },
  { code: 'BY', th: 'เบลารุส', en: 'Belarus' },
  { code: 'PL', th: 'โปแลนด์', en: 'Poland' },
  { code: 'CZ', th: 'เช็กเกีย', en: 'Czech Republic' },
  { code: 'SK', th: 'สโลวาเกีย', en: 'Slovakia' },
  { code: 'HU', th: 'ฮังการี', en: 'Hungary' },
  { code: 'RO', th: 'โรมาเนีย', en: 'Romania' },
  { code: 'BG', th: 'บัลแกเรีย', en: 'Bulgaria' },
  { code: 'MD', th: 'มอลโดวา', en: 'Moldova' },
  { code: 'RS', th: 'เซอร์เบีย', en: 'Serbia' },
  { code: 'HR', th: 'โครเอเชีย', en: 'Croatia' },
  { code: 'SI', th: 'สโลวีเนีย', en: 'Slovenia' },
  { code: 'BA', th: 'บอสเนียและเฮอร์เซโกวีนา', en: 'Bosnia and Herzegovina' },
  { code: 'ME', th: 'มอนเตเนโกร', en: 'Montenegro' },
  { code: 'MK', th: 'มาซิโดเนียเหนือ', en: 'North Macedonia' },
  { code: 'AL', th: 'แอลเบเนีย', en: 'Albania' },
  { code: 'GR', th: 'กรีซ', en: 'Greece' },
  { code: 'IT', th: 'อิตาลี', en: 'Italy' },
  { code: 'MT', th: 'มอลตา', en: 'Malta' },
  { code: 'ES', th: 'สเปน', en: 'Spain' },
  { code: 'PT', th: 'โปรตุเกส', en: 'Portugal' },
  { code: 'FR', th: 'ฝรั่งเศส', en: 'France' },
  { code: 'MC', th: 'โมนาโก', en: 'Monaco' },
  { code: 'AD', th: 'อันดอร์รา', en: 'Andorra' },
  { code: 'DE', th: 'เยอรมนี', en: 'Germany' },
  { code: 'AT', th: 'ออสเตรีย', en: 'Austria' },
  { code: 'CH', th: 'สวิตเซอร์แลนด์', en: 'Switzerland' },
  { code: 'LI', th: 'ลิกเตนสไตน์', en: 'Liechtenstein' },
  { code: 'NL', th: 'เนเธอร์แลนด์', en: 'Netherlands' },
  { code: 'BE', th: 'เบลเยียม', en: 'Belgium' },
  { code: 'LU', th: 'ลักเซมเบิร์ก', en: 'Luxembourg' },
  { code: 'GB', th: 'สหราชอาณาจักร', en: 'United Kingdom' },
  { code: 'IE', th: 'ไอร์แลนด์', en: 'Ireland' },
  { code: 'IS', th: 'ไอซ์แลนด์', en: 'Iceland' },
  { code: 'DK', th: 'เดนมาร์ก', en: 'Denmark' },
  { code: 'NO', th: 'นอร์เวย์', en: 'Norway' },
  { code: 'SE', th: 'สวีเดน', en: 'Sweden' },
  { code: 'FI', th: 'ฟินแลนด์', en: 'Finland' },
  { code: 'EE', th: 'เอสโตเนีย', en: 'Estonia' },
  { code: 'LV', th: 'ลัตเวีย', en: 'Latvia' },
  { code: 'LT', th: 'ลิทัวเนีย', en: 'Lithuania' },
  { code: 'US', th: 'สหรัฐอเมริกา', en: 'United States' },
  { code: 'CA', th: 'แคนาดา', en: 'Canada' },
  { code: 'MX', th: 'เม็กซิโก', en: 'Mexico' },
  { code: 'GT', th: 'กัวเตมาลา', en: 'Guatemala' },
  { code: 'BZ', th: 'เบลีซ', en: 'Belize' },
  { code: 'CR', th: 'คอสตาริกา', en: 'Costa Rica' },
  { code: 'PA', th: 'ปานามา', en: 'Panama' },
  { code: 'CU', th: 'คิวบา', en: 'Cuba' },
  { code: 'DO', th: 'สาธารณรัฐโดมินิกัน', en: 'Dominican Republic' },
  { code: 'JM', th: 'จาเมกา', en: 'Jamaica' },
  { code: 'BR', th: 'บราซิล', en: 'Brazil' },
  { code: 'AR', th: 'อาร์เจนตินา', en: 'Argentina' },
  { code: 'CL', th: 'ชิลี', en: 'Chile' },
  { code: 'CO', th: 'โคลอมเบีย', en: 'Colombia' },
  { code: 'PE', th: 'เปรู', en: 'Peru' },
  { code: 'VE', th: 'เวเนซุเอลา', en: 'Venezuela' },
  { code: 'EC', th: 'เอกวาดอร์', en: 'Ecuador' },
  { code: 'BO', th: 'โบลิเวีย', en: 'Bolivia' },
  { code: 'PY', th: 'ปารากวัย', en: 'Paraguay' },
  { code: 'UY', th: 'อุรุกวัย', en: 'Uruguay' },
  { code: 'EG', th: 'อียิปต์', en: 'Egypt' },
  { code: 'MA', th: 'โมร็อกโก', en: 'Morocco' },
  { code: 'DZ', th: 'แอลจีเรีย', en: 'Algeria' },
  { code: 'TN', th: 'ตูนิเซีย', en: 'Tunisia' },
  { code: 'LY', th: 'ลิเบีย', en: 'Libya' },
  { code: 'ZA', th: 'แอฟริกาใต้', en: 'South Africa' },
  { code: 'NG', th: 'ไนจีเรีย', en: 'Nigeria' },
  { code: 'KE', th: 'เคนยา', en: 'Kenya' },
  { code: 'ET', th: 'เอธิโอเปีย', en: 'Ethiopia' },
  { code: 'GH', th: 'กานา', en: 'Ghana' },
  { code: 'TZ', th: 'แทนซาเนีย', en: 'Tanzania' },
  { code: 'UG', th: 'ยูกันดา', en: 'Uganda' },
  { code: 'SN', th: 'เซเนกัล', en: 'Senegal' },
  { code: 'CI', th: 'ไอวอรีโคสต์', en: "Cote d'Ivoire" },
  { code: 'CM', th: 'แคเมอรูน', en: 'Cameroon' },
  { code: 'MZ', th: 'โมซัมบิก', en: 'Mozambique' },
  { code: 'AO', th: 'แองโกลา', en: 'Angola' },
  { code: 'ZM', th: 'แซมเบีย', en: 'Zambia' },
  { code: 'ZW', th: 'ซิมบับเว', en: 'Zimbabwe' },
  { code: 'RW', th: 'รวันดา', en: 'Rwanda' },
  { code: 'AU', th: 'ออสเตรเลีย', en: 'Australia' },
  { code: 'NZ', th: 'นิวซีแลนด์', en: 'New Zealand' },
  { code: 'FJ', th: 'ฟิจิ', en: 'Fiji' },
  { code: 'PG', th: 'ปาปัวนิวกินี', en: 'Papua New Guinea' },
  { code: 'OTHER', th: 'อื่น ๆ', en: 'Other' },
];
